id: IE54F241E
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T20:38:32.385661'
last_modified: '2022-05-30T20:38:32.385674'
parser: null
source_metadata:
  title: Dzongter Kunzang Nyima
  language: bo
  description: 'Texts by and about Dzongter Kunzang Nyima (rdzong gter kun bzang nyi
    ma, 1904–1958), the grandson and enlightened speech incarnation of Dudjom Lingpa
    (1835–1904):'
  volume:
    fE24B:
      title: A Prayer to the Precious Guru from Uḍḍiyāna That Spontaneously Fulfils
        All Wishes
      base_file: fE24B.txt
      order: 1
      parent: Guru Rinpoche Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
